### ISSUE TITLE
Exact order failed in case of incorrect order

### ISSUE THREAD

**Issue by Adorem** [dxdc/node-red-contrib-join-wait#1]
Hello,

First thanks for your node it seems to be really what I'm looking for.

But it seems the exact order is not working correctly.
In case of this Paths (Wait):
["path_1", "path_2"]
And if this arrive:
["path_2", "path_1", "path_2"]

The second part is not detected and I get 3 times the timeout.

With the following code (sending ["path_1", "path_2", "path_2", "path_1", "path_2"]) I detect the first "path_1", "path_2" but not the second:
`[{"id":"95381dc9.c8b9c","type":"inject","z":"1cc55bbe.9f4cd4","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":"","x":100,"y":600,"wires":[["6121961b.964748","4d403e03.16926","5e3a1179.8b5bc","8bb9d125.33826","740a74e2.9c761c"]]},{"id":"c2c874bd.a96468","type":"join-wait","z":"1cc55bbe.9f4cd4","name":"","paths":"[\"event_1A\", \"event_1B\"]","pathsToExpire":"","ignoreUnmatched":false,"pathTopic":"name","pathTopicType":"msg","correlationTopic":"","correlationTopicType":"msg","timeout":"10","timeoutUnits":"1000","exactOrder":"true","firstMsg":"true","mapPayload":"true","disableComplete":false,"x":820,"y":600,"wires":[["1b4b893c.2987a7"],["6adcdcde.84df34"]]},{"id":"49734310.67eb8c","type":"change","z":"1cc55bbe.9f4cd4","name":"Set event_1A","rules":[{"t":"set","p":"name","pt":"msg","to":"event_1A","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":580,"y":600,"wires":[["c2c874bd.a96468"]]},{"id":"fb85239f.3a70c","type":"change","z":"1cc55bbe.9f4cd4","name":"Set event_1B","rules":[{"t":"set","p":"name","pt":"msg","to":"event_1B","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":580,"y":660,"wires":[["c2c874bd.a96468"]]},{"id":"1b4b893c.2987a7","type":"debug","z":"1cc55bbe.9f4cd4","name":"Success","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1060,"y":580,"wires":[]},{"id":"6adcdcde.84df34","type":"debug","z":"1cc55bbe.9f4cd4","name":"Expired","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","x":1060,"y":640,"wires":[]},{"id":"6121961b.964748","type":"delay","z":"1cc55bbe.9f4cd4","name":"","pauseType":"delay","timeout":"1","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":400,"y":600,"wires":[["49734310.67eb8c"]]},{"id":"4d403e03.16926","type":"delay","z":"1cc55bbe.9f4cd4","name":"","pauseType":"delay","timeout":"2","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":400,"y":680,"wires":[["fb85239f.3a70c"]]},{"id":"5e3a1179.8b5bc","type":"delay","z":"1cc55bbe.9f4cd4","name":"","pauseType":"delay","timeout":"3","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":400,"y":720,"wires":[["fb85239f.3a70c"]]},{"id":"8bb9d125.33826","type":"delay","z":"1cc55bbe.9f4cd4","name":"","pauseType":"delay","timeout":"4","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":400,"y":640,"wires":[["49734310.67eb8c"]]},{"id":"740a74e2.9c761c","type":"delay","z":"1cc55bbe.9f4cd4","name":"","pauseType":"delay","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":400,"y":760,"wires":[["fb85239f.3a70c"]]}]`

**Comment by dxdc** [comment]
@Adorem :

If I understand you correctly, this is by design. Let me explain.

> In case of this Paths (Wait):
["path_1", "path_2"]

> If ["path_2", "path_1", "path_2"] arrives...

Actually, in this case ["path_2", "path_1"] is already enough to match so it will be sent. `path_2` (the last one) is now waiting for a `path_1` to arrive. If it doesn't arrive, it expires.

I'm not sure the behavior you're looking for? Like, if an *additional* `path_2` arrives after `path_1` and `path_2`? There are some clever ways that you can chain the wait node, but it depends on what you're after.

**Comment by dxdc** [comment]
(Please copy & paste your actual node -- this is just one from the example file -- and I can look into it also).

**Comment by Adorem** [comment]
Hi @dxdc,

Thank you for your fast answer.

My code is not only your example it's a modified version to illustrate my explanation.
The kee point is I'm using the option `Sequence order: exact order`. Then if I understand your design (or at least it's the way I would like it to work ;-) ) with this `Paths (Wait): ["path_1", "path_2"]` and If `["path_2", "path_1", "path_2"]` arrives I expect this output:
`"path_2"` arrive and goes immediately to expired output.
`"path_1"` arrive the we wait for Timeout (it can be the start of a correct sequence)
`"path_2"` arrive before the end of timeout then we have the expected sequence in the expected order and then goes to success output.
input | success output | expired output
------ | ------ | ------
path_2||path_2
path_1||
path_2|path_1, path_2|

Another example with this more complexe input: `["path_1", "path_1", "path_2", "path_1", delay greater than timeout, "path_2"]` the output will be:
input | success output | expired output
------ | ------ | ------
path_1a||
path_1b||path_1a (the first one)
path_2a|path_1b, path_2a|
path_1c||
delay||path_1c
path_2b|| path_2b

**Comment by dxdc** [comment]
@Adorem I think your idea is possible, but maybe better implemented differently. Based on the way the current functionality works, and other potential complexities, I think we should do this differently. It also opens up other options... e.g. `1, 2, 1, 1, 2`.

Here is the sample flow.

![image](https://user-images.githubusercontent.com/7200365/82893745-1db9c700-9f17-11ea-8c18-e07422ed7660.png)

This example uses the `node-red-contrib-counter` node to increment the message path, and reset it again on any expired/success node. Let me know what you think, I can add this to the examples.

```js
[{"id":"dbfa9ac5.9d6618","type":"counter","z":"f2ecc746.8566a8","name":"","init":"-1","step":"1","lower":"","upper":"","mode":"increment","outputs":1,"x":600,"y":3140,"wires":[["55ad46b9.2a9a48"]]},{"id":"1b4b1ba5.f4e8d4","type":"change","z":"f2ecc746.8566a8","name":"","rules":[{"t":"set","p":"reset","pt":"msg","to":"-1","tot":"num"}],"action":"","property":"","from":"","to":"","reg":false,"x":1140,"y":3200,"wires":[["dbfa9ac5.9d6618"]]},{"id":"66b8b98f.a48828","type":"inject","z":"f2ecc746.8566a8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":"","x":220,"y":3140,"wires":[["1f4a08ed.ab9977","27b4ffa6.0cdec","dbfa9ac5.9d6618"]]},{"id":"1801f3f.5c9ed0c","type":"join-wait","z":"f2ecc746.8566a8","name":"","paths":"[\"event_1B_0\", \"event_1A\", \"event_1B_1\"]","pathsToExpire":"","ignoreUnmatched":false,"pathTopic":"name","pathTopicType":"msg","correlationTopic":"","correlationTopicType":"msg","timeout":"10","timeoutUnits":"1000","exactOrder":"true","firstMsg":"true","mapPayload":"true","disableComplete":false,"x":900,"y":3080,"wires":[["834b89be.73cb28","1b4b1ba5.f4e8d4"],["ea64c43f.16ef08","1b4b1ba5.f4e8d4"]]},{"id":"2b1fb299.232fae","type":"change","z":"f2ecc746.8566a8","name":"Set event_1A","rules":[{"t":"set","p":"name","pt":"msg","to":"event_1A","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":610,"y":3080,"wires":[["1801f3f.5c9ed0c"]]},{"id":"76af9eb8.e99d1","type":"change","z":"f2ecc746.8566a8","name":"Set event_1B","rules":[{"t":"set","p":"name","pt":"msg","to":"\"event_1B_\" & count","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":880,"y":3140,"wires":[["1801f3f.5c9ed0c"]]},{"id":"834b89be.73cb28","type":"debug","z":"f2ecc746.8566a8","name":"Success","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1080,"y":3000,"wires":[]},{"id":"ea64c43f.16ef08","type":"debug","z":"f2ecc746.8566a8","name":"Expired","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","x":1080,"y":3040,"wires":[]},{"id":"1f4a08ed.ab9977","type":"delay","z":"f2ecc746.8566a8","name":"","pauseType":"delay","timeout":"1","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":420,"y":3080,"wires":[["2b1fb299.232fae"]]},{"id":"27b4ffa6.0cdec","type":"delay","z":"f2ecc746.8566a8","name":"","pauseType":"delay","timeout":"2","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":400,"y":3220,"wires":[["dbfa9ac5.9d6618"]]},{"id":"55ad46b9.2a9a48","type":"switch","z":"f2ecc746.8566a8","name":"","property":"count","propertyType":"msg","rules":[{"t":"gte","v":"0","vt":"num"}],"checkall":"true","repair":false,"outputs":1,"x":730,"y":3140,"wires":[["76af9eb8.e99d1"]]}]
```

**Comment by Adorem** [comment]
Maybe before going to what I need it's better to re-explain how the option `Sequence order: Exact order` is supposed to work?

Because when I read this (simulated with the example I provide you in my last message):
- Sequence order defines the criteria to evaluate the received messages. An exact match can be specified, otherwise, it will match them in any order.
> To determine the order, the timestamp on the latest valid Paths (Wait) is used, even if multiple messages arrived earlier. In this case of waiting for ["path_1", "path_2", "path_3"], the * indicates which messages are used: ["path_1", "path_2", "path_1"*, "path_2"*, "path_3"*].

All goes through the expire output:
![image](https://user-images.githubusercontent.com/38832853/82908265-08b95400-9f68-11ea-987c-084c6fe5bca3.png)
But I expect more something like that (First 1B goes to Expire output and then one message for the sequence 1A/1B going through Success output):
![image](https://user-images.githubusercontent.com/38832853/82908531-651c7380-9f68-11ea-8504-fc4f38d70b30.png)

But maybe it's not what you expect?

**Comment by dxdc** [comment]
> Maybe before going to what I need it's better to re-explain how the option Sequence order: Exact order is supposed to work?

The bigger issue @Adorem is that the plugin isn't triggering an error for your duplicate pathnames. Duplicate pathnames aren't supported. So, the behavior my be unexpected.

Currently also the behavior is as follows: once a path is expired, all paths before it are expired too.

In other words, consider an exact match for `1, 2, 3`.

In this sequence:
`1, 2, 1, 2, 3` the first 1, 2 would be expired as soon as the next `1` arrives. In other words, only the entries with `*` are considered: `1, 2, 1*, 2*, 3*`.

There are two issues I think you're raising, but primarily around duplicate paths. Let's consider this example:

`1, 2, 3, 2, 1, 3`, and suppose we are desiring an exact match for `1, 2, 1`. This gets very complicated very quickly. You could make the argument that it does match your desired sequence... but it's not trivial for how to deal with it.

As far as the duplicate paths, it's interesting, but then also raises the question of spacing. Let's rewrite this example: `1, 2, 3, 2, 1, 3` as `1, 2, 3, 2', 1', 3'` where we are using `'` to indicate the second occurrence.

If we added some counting features, we could consider a path of `1, 2, 2', 1'` to match, but the math on this gets a bit tricky. Consider this example now: `1, 1', 2, 3, 2', 1'', 3'`. Also, consider that we are looking now for the *difference* between the counts. In other words, in our path consideration of `1, 2, 2', 1'` we really mean a second two and a second one.

Also, did you try my example? I'm not sure of your exact use case but it is not trivial to think through this.

**Comment by Adorem** [comment]
Ok the kee point I do not understand before is that the plugin do not expect duplicate pathnames.

According to this I success to reach my goal with this flow:
```js
[{"id":"9b69857e.57e988","type":"inject","z":"44a778c0.bc09c8","name":"Event 1","topic":"msg.name","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":"","x":130,"y":60,"wires":[["15ba9d85.e4b572","ba962e7a.9a763"]]},{"id":"1cd56eef.8ecc61","type":"join-wait","z":"44a778c0.bc09c8","name":"","paths":"[\"event_1\", \"event_2\"]","pathsToExpire":"","ignoreUnmatched":false,"pathTopic":"path","pathTopicType":"msg","correlationTopic":"","correlationTopicType":"msg","timeout":"5","timeoutUnits":"1000","exactOrder":"true","firstMsg":"true","mapPayload":"true","disableComplete":false,"x":840,"y":140,"wires":[["19da9a78.dcabe6","65ec9361.ea293c"],["75c377e9.e6d328","65ec9361.ea293c"]]},{"id":"19da9a78.dcabe6","type":"debug","z":"44a778c0.bc09c8","name":"Success","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":1040,"y":100,"wires":[]},{"id":"75c377e9.e6d328","type":"debug","z":"44a778c0.bc09c8","name":"Expired","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"true","targetType":"full","x":1040,"y":180,"wires":[]},{"id":"60e232c5.8160dc","type":"traffic","z":"44a778c0.bc09c8","name":"Traffic sample","property_allow":"payload","filter_allow":"GO","ignore_case_allow":false,"negate_allow":false,"send_allow":false,"property_stop":"payload","filter_stop":"STOP","ignore_case_stop":false,"negate_stop":false,"send_stop":false,"default_start":false,"differ":false,"x":460,"y":220,"wires":[["98b7e67e.5133d8"]]},{"id":"15ba9d85.e4b572","type":"change","z":"44a778c0.bc09c8","name":"Set GO","rules":[{"t":"set","p":"payload","pt":"msg","to":"GO","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":280,"y":120,"wires":[["60e232c5.8160dc"]]},{"id":"16237941.47fb17","type":"change","z":"44a778c0.bc09c8","name":"Set STOP","rules":[{"t":"set","p":"payload","pt":"msg","to":"STOP","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":280,"y":160,"wires":[["60e232c5.8160dc"]]},{"id":"b290bbb6.c23338","type":"inject","z":"44a778c0.bc09c8","name":"Event 2","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":"","x":130,"y":220,"wires":[["60e232c5.8160dc"]]},{"id":"65ec9361.ea293c","type":"link out","z":"44a778c0.bc09c8","name":"","links":["d67dda18.09f658"],"x":995,"y":140,"wires":[]},{"id":"d67dda18.09f658","type":"link in","z":"44a778c0.bc09c8","name":"","links":["65ec9361.ea293c"],"x":100,"y":160,"wires":[["16237941.47fb17"]]},{"id":"98b7e67e.5133d8","type":"change","z":"44a778c0.bc09c8","name":"Set event_2","rules":[{"t":"set","p":"path","pt":"msg","to":"event_2","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":650,"y":220,"wires":[["1cd56eef.8ecc61"]]},{"id":"ba962e7a.9a763","type":"change","z":"44a778c0.bc09c8","name":"Set event_1","rules":[{"t":"set","p":"path","pt":"msg","to":"event_1","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":650,"y":60,"wires":[["1cd56eef.8ecc61"]]}]
```

Thanks for your time and help.

**Comment by dxdc** [comment]
Thanks @Adorem. I'll make some changes to make this more clear for the next release.

Also note: 
You can use `msg.name` (instead of `msg.path`) for your Paths topic to simplify things.

**Comment by dxdc** [comment]
@Adorem I just pushed an update to this package which adds two important features:

1. Prevents duplicate pathnames
2. Adds regex-based path matching. I'm not sure if this would be useful for you or not, but it's something I've been meaning to get to.

**Comment by andrejev1** [comment]
Hi @dxdc,

first thank you for very useful and really well documented node. It's priceless for newbies. :)

However, I've run into exactly the same problem with EXACT order as @Adorem initialy posted. 

So if this is required exact Paths (Wait):
["path_1", "path_2"]

And if this arrives:
["path_2", "path_1", "path_2"]

I would expect first path_2 to be ignored, but path_1 and path_2, which follow, recognized as sucessful.

If this behaviour is "by design" and will not be changed, do you know any other solution to achive this? 

Thank you in advance!

**Comment by dxdc** [comment]
@andrejev1 can you post an example flow which reproduces your issue?

**Comment by andrejev1** [comment]
@dxdc , sure, here it is.

`[{"id":"7382168d.c47858","type":"inject","z":"eb66570f.f00e28","name":"event2","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":"","topic":"","payload":"","payloadType":"date","x":170,"y":320,"wires":[["93c1545b.dca6f8"]]},{"id":"3b8f6807.956d78","type":"debug","z":"eb66570f.f00e28","name":"","active":true,"tosidebar":true,"console":false,"complete":"true","x":750,"y":300,"wires":[]},{"id":"5866d421.7eb66c","type":"inject","z":"eb66570f.f00e28","name":"event1","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":"","topic":"","payload":"","payloadType":"date","x":170,"y":260,"wires":[["8d0b69cc.b2b228"]]},{"id":"8d0b69cc.b2b228","type":"change","z":"eb66570f.f00e28","name":"Set path_1","rules":[{"t":"set","p":"paths","pt":"msg","to":"path_1","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":370,"y":260,"wires":[["5f87c222.3f317c"]]},{"id":"93c1545b.dca6f8","type":"change","z":"eb66570f.f00e28","name":"Set path_2","rules":[{"t":"set","p":"paths","pt":"msg","to":"path_2","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":370,"y":320,"wires":[["5f87c222.3f317c"]]},{"id":"5f87c222.3f317c","type":"join-wait","z":"eb66570f.f00e28","name":"","paths":"[\"path_1\", \"path_2\"]","pathsToExpire":"","ignoreUnmatched":false,"pathTopic":"paths","pathTopicType":"msg","correlationTopic":"","correlationTopicType":"msg","timeout":"10","timeoutUnits":"1000","exactOrder":"true","firstMsg":"true","mapPayload":"false","disableComplete":false,"x":580,"y":300,"wires":[["3b8f6807.956d78"],[]]}]`

Just inject event2, event1 and event2 within 10 seconds. There is no 'sucess output'.

**Comment by dxdc** [comment]
@Adorem @andrejev1 really appreciate you filing this bug report.

After @andrejev1's latest flow, I discovered another bug that caused me to re-think the whole process. @Adorem -- back when you first filed this, I think you may also have been referring to the same issue that @andrejev1 mentioned but I didn't quite understand at that time.

Understanding the correct order of paths and when to expire them was complicated to work through. I'm not convinced I've developed the most optimal solution, but from my testing it does seem to work. I addressed a number of logic updates, and even provided now support for duplicate paths.

For example, you can now specify `['path1', 'path1', 'path2']` to be called in an exact order or any order... and even use regex!

I published a new release to NPM. Please let me know if you have any updates or changes after your own testing.

**Comment by andrejev1** [comment]
@dxdc, I'm glad to hear from you! And thank you for the fix. :)

I use Node Red and your node-red-contrib-join-wait from Home Assistant. I wanted to grap new version to test it, but it's not shown in the palette (some other nodes show updates). I'm not sure about the entire process. Has everything been done/merged/published at your side? 

![image](https://user-images.githubusercontent.com/74569965/102122002-2b985080-3e45-11eb-870f-c3598921f2ef.png)

There is probably another question related to exact order mode only. It's about timer, or to be more precise reseting timer. I assume in v0.3.4 timer starts when the first path arrives (being valid or not). In some scenarious it would be useful to reset the timer (or start it) when the first valid path arrives.

For example: path_1 arrives when an API call is triggered, and path_2 when it is finished. A scenario would be to wait predefined time for path_2 but ignore all others (prior path_1) as they might be unrelated. 

I don't know how this matches with your idea about this node and its behaviour. I've already solved my problem with traffic light node, but it might be interesting.

**Comment by dxdc** [comment]
> I'm not sure about the entire process. Has everything been done/merged/published at your side?

Yes, but the built in NodeRed manager doesn't update as fast as npm. It should be ready for you to test now.

> I assume in v0.3.4 timer starts when the first path arrives (being valid or not). In some scenarious it would be useful to reset the timer (or start it) when the first valid path arrives.

You don't need to worry about how the timer is working internally. From a practical point of view, in 'exact' mode, consider we are waiting for paths ["path1", "path2", "path3].

- If anything except "path1" arrives, it is expired immediately
- If "path1" arrives, a second "path1" will lead the expiration of the first "path1".
- If "path1" arrives, then "path2", the only things that will not lead to further expiration are "path2" or "path3". I realize some people may not like the idea that duplicate paths are being handled like this, but may be able to add an option for this kind of handling in future.
- If you use the `msg.complete` option, or an expirePath, it will expire immediately.

Let me know how this aligns with your use case. I'm working on several robustness improvements as well.

**Comment by dxdc** [comment]
> If "path1" arrives, then "path2", the only things that will not lead to further expiration are "path2" or "path3". I realize some people may not like the idea that duplicate paths are being handled like this, but may be able to add an option for this kind of handling in future.

This should be:

The only things that will not lead to further expiration are "path3".  This is the only way I was able to implement handling of duplicate paths. I'm going to update the docs soon as well as push some changes, will keep this thread updated as well.

**Comment by dxdc** [comment]
Latest changes pushed.

**Comment by andrejev1** [comment]
@dxdc hi!
I was able to update to version 0.4.5. Here are my findings:
1.	Initial bug is solved (if p1+p2 are required p1+p1+p2 now returns success output).

2.	There is also no problem with timeouts (as the 2nd p1 restarts the timer so p2 has full time to come).

3.	I also think it’s better not to support ANY duplicates as things can get fishy. If this was needed I would opt for a solution where paths that can reoccur are explicitly marked.  E.g. ["p1", "p2*", "p3"]  Only p2 could reoccur in this case.

4.	I think it would also be useful to have separate outputs for expiration caused by unexpected paths and timeout.

With this last add-on I would be able to implement my use case only with join-wait node. Just to remember, I need to ignore potential p2 (API call finished) until p1 (API call triggered) is received and then wait for p2 or timeout. The first part now works, but not the second, because I don’t know if there was timeout or another p1 came along.

Anyway, your node is great and these are only my 2 cents if there is something useful for you. Thank you for solving the bug and keep up good work!

**Comment by dxdc** [comment]
> Initial bug is solved (if p1+p2 are required p1+p1+p2 now returns success output).

Great.

> There is also no problem with timeouts (as the 2nd p1 restarts the timer so p2 has full time to come).

Great.

> I also think it’s better not to support ANY duplicates as things can get fishy. If this was needed I would opt for a solution where paths that can reoccur are explicitly marked. E.g. ["p1", "p2*", "p3"] Only p2 could reoccur in this case.

- For "exact" order, paths are only valid when explicitly marked. E.g., ["p1", "p1", "p2"]. In this case, a third "p1", e.g., ["p1", "p1", , "p1", "p2"] would be invalid.

This gets a little more complicated for 'regex' paths, as 'regex' is greedy from left to right.

- For "any order", duplicates are permitted. This is because any order defines a minimum criteria. E.g., if we are looking for ["p1", "p1", "p2"] and ["p1", "p1", "p3", "p1", "p2"] is received, this is still considered valid.

> I think it would also be useful to have separate outputs for expiration caused by unexpected paths and timeout.

Timeouts are sent to the expired output (lower output = expired, top output = success). Unexpected paths can be ignored -- or -- if the 'warn' option is enabled, could be caught by the "catch" node.

> With this last add-on I would be able to implement my use case only with join-wait node. Just to remember, I need to ignore potential p2 (API call finished) until p1 (API call triggered) is received and then wait for p2 or timeout. The first part now works, but not the second, because I don’t know if there was timeout or another p1 came along.

I'm not sure why exact order of ["p1", "p2"] will not work for you in the existing set up.

I'm open to other changes if needed as well, just want to be sure we think through it all. And, if you're able to post some working flows on the wiki that would be great for the community.

**Comment by dxdc** [comment]
Pushed another branch which expires the 'any order' items a bit earlier, if needed.

**Comment by andrejev1** [comment]
@dxdc , sorry for late response. I've just upgraded to v0.5.0 and everything works as expected. Thank you!
