### ISSUE TITLE
Feature request: combine all input messages

### ISSUE THREAD

**Issue by mvandenabeele** [dxdc/node-red-contrib-join-wait#10]
First off: thanks for this node. I saw your discussion on the node-red forum and I think you're right. This should be a standard node. 

I think this node could solve even more problems if there were an option to combine all incoming messages and send the resulting object out when all paths are received.

Say I have { 'topic': 'weight', 'weight':80 } and {'topic': 'impodence', 'impodence': 500}. The join-wait node waits for ['weight', 'impodence'] paths. When both messages are received, the output would be { 'topic': 'impodence', 'weight': 80, 'impodence': 500 }. Notice the topic could come from the first or the last message, depending on the already existing configuration.

**Comment by dxdc** [comment]
@mvandenabeele  thanks for the feedback. Did you review the README? I think this may already be doable in the current implementation.

> Merged data defines how the data from msg.paths (or, another designed Paths topic) will be returned. Either, it can be merged in its original form, or, it can be overwritten with each respective msg.payload. This merged data is then appended to the Base message.

I think based on your request, you will be better off using another node (like the function node) to post process your data. You can vary the order of injection and you will see the topic change in the final payload.

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/7200365/222914611-d1c0c28f-dd89-411d-bb91-c04ddad23379.png">


```
[{"id":"1a03cac9695720f3","type":"join-wait","z":"431a0dd9.b9eea4","name":"","paths":"[\"weight\", \"impodence\"]","pathsToExpire":"","useRegex":false,"warnUnmatched":false,"pathTopic":"payload.topic","pathTopicType":"msg","correlationTopic":"","correlationTopicType":"msg","timeout":"1","timeoutUnits":"60000","exactOrder":"false","firstMsg":"true","mapPayload":"true","disableComplete":false,"persistOnRestart":false,"x":1140,"y":120,"wires":[["83061129b9c4d99f"],[]]},{"id":"fcfd15efed7e9465","type":"inject","z":"431a0dd9.b9eea4","name":"{\"topic\":\"weight\",\"weight\":80}","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"topic\":\"weight\",\"weight\":80}","payloadType":"json","x":840,"y":160,"wires":[["1a03cac9695720f3"]]},{"id":"5b981738be068dcb","type":"inject","z":"431a0dd9.b9eea4","name":"{\"topic\": \"impodence\", \"impodence\": 500}","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"topic\":\"impodence\",\"impodence\":500}","payloadType":"json","x":840,"y":320,"wires":[["1a03cac9695720f3"]]},{"id":"e860340d11ef0ad0","type":"debug","z":"431a0dd9.b9eea4","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1470,"y":60,"wires":[],"info":"Log the results of the processing in the debug console."},{"id":"83061129b9c4d99f","type":"function","z":"431a0dd9.b9eea4","name":"function","func":"let mergedPayload = {};\nif (msg[\"payload.topic\"] && typeof msg[\"payload.topic\"] === 'object') {\n    mergedPayload = Object.assign(mergedPayload, ...Object.values(msg[\"payload.topic\"]));\n    // optional:\n    // delete msg[\"payload.topic\"];\n}\nmsg.payload = Object.assign(mergedPayload, msg.payload);\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":1300,"y":120,"wires":[["e860340d11ef0ad0"]]}]
```

**Comment by mvandenabeele** [comment]
@dxdc Thanks for the quick sample. I see what your node is doing and how the function node changes the output to my desired form, but I still don't get the explanation in the readme after rereading it twice.  I'm not that experienced whit node-red but it seems as if there's always at least one function node needed to get it to work as you want, which defeats the purpose of using node-red. That's not your fault though. Thanks again for your contribution!

**Comment by dxdc** [comment]
> I'm not that experienced whit node-red but it seems as if there's always at least one function node needed to get it to work as you want, which defeats the purpose of using node-red. 

As you rightly point out, everyone's use case ends up being pretty unique.

If all feature requests were added, then it would be hard to use and maintain since less than 1% of the features would be used by the majority of users. Even this node is getting a bit unwieldy as you point out, but I haven't had time to update the documentation or code. :)

The concept behind NR is you can string a large number of nodes together to build anything you desire (including writing your own). So each node does something simple and straightforward (a "widget"), and each widget has discrete and testable inputs and outputs.
