### ISSUE TITLE
When one msg timeouts, all the messages go to the 'expired' output

### ISSUE THREAD

**Issue by PlkMarudny** [dxdc/node-red-contrib-join-wait#6]
How is it supposed to work? I have a simplest setup and it does not work as if: when the delayed message expires, both messages go to the "expired" output.

![image](https://user-images.githubusercontent.com/4361591/104317321-3e12b200-54f7-11eb-9f8c-fe66de0facb4.png)

`[{"id":"34367e56.7509c2","type":"join-wait","z":"cf34b7cb.9183b8","name":"","paths":"[\"path_1\", \"path_2\"]","pathsToExpire":"","ignoreUnmatched":false,"pathTopic":"paths","pathTopicType":"msg","correlationTopic":"_msgid","correlationTopicType":"msg","timeout":"3000","timeoutUnits":1,"exactOrder":"false","firstMsg":"true","mapPayload":"true","disableComplete":false,"x":600,"y":220,"wires":[["dbb5dc6f.0524"],["2c925d4f.8f424a"]]},{"id":"35386928.fb21de","type":"inject","z":"cf34b7cb.9183b8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":150,"y":240,"wires":[["1c9f51ea.ab8536","d584d77b.bb42e8"]]},{"id":"1c9f51ea.ab8536","type":"change","z":"cf34b7cb.9183b8","name":"v1","rules":[{"t":"set","p":"paths","pt":"msg","to":"path_1","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":290,"y":220,"wires":[["34367e56.7509c2"]]},{"id":"9363809b.0165f8","type":"change","z":"cf34b7cb.9183b8","name":"v2","rules":[{"t":"set","p":"paths","pt":"msg","to":"path_2","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":450,"y":300,"wires":[["34367e56.7509c2"]]},{"id":"dbb5dc6f.0524","type":"debug","z":"cf34b7cb.9183b8","name":"on_time","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"paths","targetType":"msg","statusVal":"","statusType":"auto","x":800,"y":160,"wires":[]},{"id":"2c925d4f.8f424a","type":"debug","z":"cf34b7cb.9183b8","name":"expired","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"paths","targetType":"msg","statusVal":"","statusType":"auto","x":800,"y":280,"wires":[]},{"id":"d584d77b.bb42e8","type":"delay","z":"cf34b7cb.9183b8","name":"","pauseType":"delay","timeout":"5","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":300,"y":300,"wires":[["9363809b.0165f8"]]}]`

**Comment by dxdc** [comment]
@PlkMarudny there is a timeout configured in the settings. This timeout is the maximum "window" of time that a successful message sequence must arrive within.

In your case, this is set to 3000 ms.

0:00 - v1 arrives.
0:03 - 3000 ms after v1 is sent, the message sequence has not completed, so v1 is expired.
0:05 - v2 is sent (5 second delay from v1)
0:08 - v2 is expired

If you want this to work, you need to increase your timeout to accommodate v1 and v2 arriving within the same window, or decrease your delay. Please see the README for some other working examples.

<img width="1258" alt="Screen Shot 2021-01-12 at 7 30 17 AM" src="https://user-images.githubusercontent.com/7200365/104320733-54dde800-54a8-11eb-86c2-c593b77537b1.png">

**Comment by PlkMarudny** [comment]
OK, thanks, I got it, but this means all the messages go to one of the outputs, never are splitted on those that come within the window and those being late, right?

And what about a case like below? It is just one message, it should expire I believe? But it goes to the upper output eventually.

![image](https://user-images.githubusercontent.com/4361591/104324651-23453b00-5501-11eb-90dc-fdc50b2ccde9.png)

[{"id":"b99c6b18.5f6688","type":"inject","z":"cf34b7cb.9183b8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":140,"y":160,"wires":[["981e6164.415a6"]]},{"id":"981e6164.415a6","type":"delay","z":"cf34b7cb.9183b8","name":"","pauseType":"delay","timeout":"6","timeoutUnits":"seconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":300,"y":160,"wires":[["e568a82.54471d8"]]},{"id":"e568a82.54471d8","type":"change","z":"cf34b7cb.9183b8","name":"v2","rules":[{"t":"set","p":"paths","pt":"msg","to":"path_2","tot":"str"}],"action":"","property":"","from":"","to":"","reg":false,"x":450,"y":160,"wires":[["e7cf6585.c4487"]]},{"id":"e7cf6585.c4487","type":"join-wait","z":"cf34b7cb.9183b8","name":"","paths":"[\"path_2\"]","pathsToExpire":"","ignoreUnmatched":false,"pathTopic":"paths","pathTopicType":"msg","correlationTopic":"","correlationTopicType":"msg","timeout":"3000","timeoutUnits":1,"exactOrder":"false","firstMsg":"true","mapPayload":"true","disableComplete":false,"x":600,"y":160,"wires":[["9ae4f00c.d4c9b"],["72a7498b.3d758"]]},{"id":"9ae4f00c.d4c9b","type":"debug","z":"cf34b7cb.9183b8","name":"on_time","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"paths","targetType":"msg","statusVal":"","statusType":"auto","x":780,"y":120,"wires":[]},{"id":"72a7498b.3d758","type":"debug","z":"cf34b7cb.9183b8","name":"expired","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"paths","targetType":"msg","statusVal":"","statusType":"auto","x":780,"y":200,"wires":[]}]

**Comment by dxdc** [comment]
> OK, thanks, I got it, but this means all the messages go to one of the outputs, never are splitted on those that come within the window and those being late, right?

The window is constantly shifting to evaluate the distance between the first and last message. If you look at the README, you'll see several cases of a success and expired output. They won't all go to the same output, necessarily.

> And what about a case like below? It is just one message, it should expire I believe? 

I think your confusion is that the window is shifting. It is not the number of seconds since the timestamp was clicked (this would be impossible to know). It is the number of seconds between the first and last message received by `join-wait`. If it exceeds the maximum allowable number of seconds, then it will chop the first message and evaluate again.

If you wanted to evaluate the number of seconds from a fixed time (say, from deployment) that is a much, much easier use case, you wouldn't need this node.

**Comment by PlkMarudny** [comment]
That's correct, thank you.
