### ISSUE TITLE
feature request: retain state after restart

### ISSUE THREAD

**Issue by noumenon272** [dxdc/node-red-contrib-join-wait#7]
First, this node is great and I’ve been using it a bunch in my home automation projects.

With my use case I have several timeouts that are hours long while it waits for a second event. If I am futzing with node red (as I tend to be) and restart the instance I will lose my waits. I’d love to have it pick back up where it left off upon reboot.

the stoptimer-varidelay node has a useful interface for this feature.
https://flows.nodered.org/node/node-red-contrib-stoptimer-varidelay

thanks for considering!

**Comment by dxdc** [comment]
@noumenon272 This is an interesting idea. I can see how it would be useful for certain cases. Essentially, what I've done is to just retain/restore the queue. I just published a new beta release.

From your ~/.node-red folder, type:
`npm install node-red-contrib-join-wait@0.5.2-beta.0`

Then restart nodeRED and you will see the new option. Just 'tick' the setting, deploy, and it will save the queue upon a restart and restore it upon load. I had to add some handling for cases where a user can (also) toggle this setting on/off as part of their redeployment.

![image](https://user-images.githubusercontent.com/7200365/106362252-6b2cd600-62e7-11eb-9d41-03e4dac0c207.png)

Please let me know your feedback after thorough testing.

**Comment by noumenon272** [comment]
great! thanks. i’ll check it out.

**Comment by noumenon272** [comment]
this seems to be working well for me. all of my long wait times have to do with sun events and I’ve tested it several times over the past few days and it seems to work great!

thanks

**Comment by dxdc** [comment]
Thanks for testing @noumenon272. I made a small tweak and pushed the release. There is no functional difference between the version you have and the release version.
