### ISSUE TITLE
Missing option: "And After Every Subsequent"

### ISSUE THREAD

**Issue by Putzeimer** [dxdc/node-red-contrib-join-wait#9]
Hi, just stumbled upon your node. Looks great at first glance, but I'm missing the option "_And After Every Subsequent_" available in node-red's core join node.

Here's my use case:
I store options for several flows in MQTT. Let's say I have a custom timer with the options `name` and `active.`
The topic looks like `timer/timername/optionname`, so 2 different timers have these 4 topics:

- `timer/timer1/name`
- `timer/timer1/active`
- `timer/timer2/name`
- `timer/timer2/active`

To be able to initialize a timer, I need all options from that timer together, so I use a _join-wait_ node with `Paths (wait)` set to:
`["^timer/[^/]+/name$", "^timer/[^/]+/active$"]`
Furthermore I need to tell the node that messages with the same timername belongs together. So I set `Correlation topic` to:
`$split( msg.topic, '/' )[1]`
This works great, but when the timer is now turned on/off, only the `timer/timername/active` topic is triggered again and the _join-wait_ node runs into timeout.
Any idea how to achieve this with your node?

One other (related) thing:
Let's imagine this incoming message order:
```
timer/timer1/active = false
timer/timer1/active = true
timer/timer1/name = "working day"
```
After the third message arrives (within timeout), this object will be send to `success` output as expected:
`{ "timer/timer1/active": true, "timer/timer1/name": "working day" }`
However, immediately after the second message arrives, the `expired` output is triggered with the value from the first message (false). The object of that message has the same format as a timeout message, so I see no way to determine if the message is a timeout message (=> error) or a duplicate message (=> conventional).
I suggest to either provide a way to turn the duplicate messages of (favored) ot at least to make them distinguishable by adding some kind of "type" property.

Cheers
Putzeimer
<details> 
<summary>Example flow:</summary>

```
[
    {
        "id": "51b4898c1305055e",
        "type": "join-wait",
        "z": "a2b23fab59d842d2",
        "name": "",
        "paths": "[\"^timer/[^/]+/name$\", \"^timer/[^/]+/active$\"]",
        "pathsToExpire": "",
        "useRegex": true,
        "warnUnmatched": false,
        "pathTopic": "topic",
        "pathTopicType": "msg",
        "correlationTopic": "$split( msg.topic, '/' )[1]",
        "correlationTopicType": "jsonata",
        "timeout": "5",
        "timeoutUnits": "1000",
        "exactOrder": "false",
        "firstMsg": "true",
        "mapPayload": "true",
        "disableComplete": false,
        "persistOnRestart": false,
        "x": 1200,
        "y": 1140,
        "wires": [
            [
                "e2e43594f7036dfc"
            ],
            [
                "2e213fc0dc7dd1d1"
            ]
        ]
    },
    {
        "id": "3d1e6f711c80c2f1",
        "type": "inject",
        "z": "a2b23fab59d842d2",
        "name": "",
        "props": [
            {
                "p": "topic",
                "vt": "str"
            },
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "timer/timer1/name",
        "payload": "working day",
        "payloadType": "str",
        "x": 950,
        "y": 1020,
        "wires": [
            [
                "51b4898c1305055e"
            ]
        ]
    },
    {
        "id": "ece7ee6536a75c1f",
        "type": "inject",
        "z": "a2b23fab59d842d2",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "timer/timer1/active",
        "payload": "true",
        "payloadType": "bool",
        "x": 920,
        "y": 1060,
        "wires": [
            [
                "51b4898c1305055e"
            ]
        ]
    },
    {
        "id": "a6ebf4bc12dfde68",
        "type": "inject",
        "z": "a2b23fab59d842d2",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "timer/timer1/active",
        "payload": "false",
        "payloadType": "bool",
        "x": 920,
        "y": 1100,
        "wires": [
            [
                "51b4898c1305055e"
            ]
        ]
    },
    {
        "id": "4604c00887309857",
        "type": "inject",
        "z": "a2b23fab59d842d2",
        "name": "",
        "props": [
            {
                "p": "topic",
                "vt": "str"
            },
            {
                "p": "payload"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "timer/timer2/name",
        "payload": "weekend",
        "payloadType": "str",
        "x": 940,
        "y": 1180,
        "wires": [
            [
                "51b4898c1305055e"
            ]
        ]
    },
    {
        "id": "37811ebd3d10abb4",
        "type": "inject",
        "z": "a2b23fab59d842d2",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "timer/timer2/active",
        "payload": "true",
        "payloadType": "bool",
        "x": 920,
        "y": 1220,
        "wires": [
            [
                "51b4898c1305055e"
            ]
        ]
    },
    {
        "id": "640ef0c3dd44399d",
        "type": "inject",
        "z": "a2b23fab59d842d2",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "timer/timer2/active",
        "payload": "false",
        "payloadType": "bool",
        "x": 920,
        "y": 1260,
        "wires": [
            [
                "51b4898c1305055e"
            ]
        ]
    },
    {
        "id": "e2e43594f7036dfc",
        "type": "debug",
        "z": "a2b23fab59d842d2",
        "name": "success",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 1380,
        "y": 1120,
        "wires": []
    },
    {
        "id": "2e213fc0dc7dd1d1",
        "type": "debug",
        "z": "a2b23fab59d842d2",
        "name": "expired",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 1380,
        "y": 1160,
        "wires": []
    }
]
```
</details>

**Comment by dxdc** [comment]
@Putzeimer - I don't think I fully understand your use case. It sounds like you want messages to be repeated? That runs somewhat counter to how this node works - essentially looking for groups of messages to arrive in a sequence and time interval - and taking an action if that happens.

I can envision a couple scenarios you might be trying to achieve, for example:

1. If /timer1/active is true, then allow messages to go through. Else, do not allow messages to go through.
2. If /timer1/active is true *and* /timer1/name message arrives within n seconds, then allow messages to go through.

That being said, I'm not convinced this node will be the best to suit your use case. I might suggest, instead, renaming the payload to include the true/false option. Then your paths could include the true/false value and that might help you with message parsing.

Alternatively, if you only want messages to go through when a status is true or false, you could use a gate node. There is a really nice example of that here: https://discourse.nodered.org/t/join-wait-node-timeout-feature-request/27633/18

**Comment by Putzeimer** [comment]
No, that is not what I'm talking about. I don't want that messages should only go through if the payload has a specific value. The property "active" is just an example, it could also be:
```
timer/timer1/param1 = val1
timer/timer1/param2 = val2
```

The "_and after every subsequent_" option from the original join node in "_manual_" mode works like so:
(The "_After a number of message parts_" is set to "2" for this example)
1st message: `timer/timer1/param1 = val1`
=> `no output`
2nd message: `timer/timer1/param2 = val2`
=> `output: { "timer/timer1/param1": "val1", "timer/timer1/param2": "val2" }`
3rd message: `timer/timer1/param1 = new val`
=> `output: { "timer/timer1/param1": "new val", "timer/timer1/param2": "val2" }`
So the node first triggers after it receives 2 messages and then again after the 3rd message (and every subsequent message). Your node, in contrary, "resets" after all defined topics are received. All topics needs to be send again then.

The problem with the core node is, that it has no intelligence in inspecting the message it receives. So it would trigger after receiving this 2 messages also:
```
timer/timer1/param1 = val1
timer/timer2/param2 = val2
```
But that isn't a "full set" of properties (which is "_param1_" **and** "_param2_" from the **same** timer).

Your node is great in inspecting the topics and does all the core node lacks, except that it shouldn't reset after a success message is created.

To be more clear: In the example flow I added to my first post: If you press the upper 3 inject nodes (with timer/timer1) from top to bottom within 5 seconds, the output is:
`{ "timer/timer1/name": "working day", "timer/timer1/active": true }`
And after 5 seconds:
`{ "timer/timer1/active": false }`

The desired behaviour is:
`{ "timer/timer1/name": "working day", "timer/timer1/active": true }` (after injecting top and middle node)
`{ "timer/timer1/name": "working day", "timer/timer1/active": false }` (after injecting bottom node)
And after 5 seconds:
`no output`

**Comment by dxdc** [comment]
> Your node, in contrary, "resets" after all defined topics are received. All topics needs to be send again then.

Correct. This is the intended behavior. The purpose of the node is to receive a specific number of messages within a time interval. That is not your use case, and further, trying to implement something like that would be somewhat counter intuitive to how the node currently works. I have a suggestion for you below, but otherwise, I would suggest posing your problem on the nodered discourse.

> The desired behaviour is:

You're looking for the core Join node. Here is how to set it up, with some changes perhaps based on your use case.

1. I'm not sure you'll need `after every subsequent message`, but you could test that of course.
2. You may need to filter your output into discrete timers. So, timer1 data goes to a timer1 join node, timer2 data goes to a timer2 join node, etc.

```
[{"id":"e3bb26f9.a881a8","type":"join","z":"49d0324f.eb4e2c","name":"Join","mode":"custom","build":"object","property":"payload","propertyType":"msg","key":"name","joiner":"\\n","joinerType":"str","accumulate":false,"timeout":"","count":"5","reduceRight":false,"reduceExp":"","reduceInit":"","reduceInitType":"","reduceFixup":"","x":1270,"y":120,"wires":[["8746a8da.45e228"]]}]
```
